### ISSUE TITLE
Hard coded joint parameters in foot and talus

### ISSUE THREAD

**Issue by melund** [AnyBody-Research-Group/LowerExtremity-RBF-scaling#1]
The joint parameters of the foot and talus have been hard coded, so they can be changed in footpos study. However, this causes a problem with the static based (non-optimized) model. We need to find way to break expressions when needed.

**Comment by saeeddf** [comment]
Great job, if I understood well, now we have a detailed foot like what we had for hand. but I could not get what you meant by having problem with static based model...
